USE ODS;

DROP TABLE IF EXISTS ODS.ODS_DM_AGENTES_CC;

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_AGENTES_CC(
ID_AGENTE_CC INT(10) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
DE_AGENTE_CC VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS.ODS_DM_DEPARTAMENTOS_CC;

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_DEPARTAMENTOS_CC(
ID_DEPARTAMENTO_CC INT(10) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
DE_DEPARTAMENTO_CC VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS.ODS_HC_LLAMADAS;

CREATE TABLE IF NOT EXISTS ODS.ODS_HC_LLAMADAS (
ID_LLAMADA INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_IVR INT(11),
TELEFONO_LLAMADA BIGINT(10) UNSIGNED,
ID_CLIENTE INT(11),
FC_INICIO_LLAMADA DATETIME,
FC_FIN_LLAMADA DATETIME,
ID_DEPARTAMENTO_CC INT(10) UNSIGNED,
FLG_TRANSFERIDO TINYINT(1),
ID_AGENTE_CC INT(10) UNSIGNED,
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llamadas_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llamadas_cli FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llamadas_depar_idx (ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llamadas_depar FOREIGN KEY (ID_DEPARTAMENTO_CC)
	REFERENCES ODS.ODS_DM_DEPARTAMENTOS_CC (ID_DEPARTAMENTO_CC) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llamadas_agente_idx (ID_AGENTE_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llamadas_agente FOREIGN KEY (ID_AGENTE_CC)
	REFERENCES ODS.ODS_DM_AGENTES_CC (ID_AGENTE_CC) ON DELETE NO ACTION ON UPDATE NO ACTION;

