USE ODS;

DROP TABLE IF EXISTS ODS.ODS_DM_PRODUCTOS;

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_PRODUCTOS(
ID_PRODUCTO INT(10) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
DE_PRODUCTO VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS.ODS_DM_CANALES;

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_CANALES(
ID_CANAL INT(10) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
DE_CANAL VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS.ODS_HC_SERVICIOS;

CREATE TABLE IF NOT EXISTS ODS.ODS_HC_SERVICIOS (
ID_SERVICIO INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT(11),
ID_PRODUCTO INT(10) UNSIGNED,
PUNTO_ACCESO VARCHAR(512),
ID_CANAL INT(10) UNSIGNED,
ID_AGENTE INT(11) UNSIGNED,
ID_DIRECCION_SERVICIO INT(10) UNSIGNED,
FC_INICIO DATETIME,
FC_INSTALACION DATETIME,
FC_FIN DATETIME,
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_cli FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE) ON DELETE NO ACTION ON UPDATE NO ACTION;
    
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_pro_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_pro FOREIGN KEY (ID_PRODUCTO)
	REFERENCES ODS.ODS_DM_PRODUCTOS (ID_PRODUCTO) ON DELETE NO ACTION ON UPDATE NO ACTION;
    
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_canal_idx (ID_CANAL ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_canal FOREIGN KEY (ID_CANAL)
	REFERENCES ODS.ODS_DM_CANALES (ID_CANAL) ON DELETE NO ACTION ON UPDATE NO ACTION;
    
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_agente_idx (ID_AGENTE ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_agente FOREIGN KEY (ID_AGENTE)
	REFERENCES ODS.ODS_DM_AGENTES_CC (ID_AGENTE_CC) ON DELETE NO ACTION ON UPDATE NO ACTION;    
    
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_dirserv_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_dirserv FOREIGN KEY (ID_DIRECCION_SERVICIO)
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION) ON DELETE NO ACTION ON UPDATE NO ACTION;



