/* Rellenamos la dimension agente desde la tabla de llamadas */
INSERT INTO ODS.ODS_DM_AGENTES_CC (DE_AGENTE_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)), 
 NOW(),
 NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE LENGTH(TRIM(AGENT)) <> 0;

INSERT INTO ODS.ODS_DM_AGENTES_CC  VALUES (9999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS.ODS_DM_AGENTES_CC  VALUES (9998, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS.ODS_DM_AGENTES_CC;

INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(SERVICE)), 
 NOW(),
 NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE LENGTH(TRIM(SERVICE)) <> 0;

INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC  VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC  VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;
ANALYZE TABLE ODS.ODS_DM_DEPARTAMENTOS_CC;

/* Comprobamos que numeros de telefono coinciden con los refelajados en la dimension de clientes, esta
consulta no devuelve ninguna coincidencia 
*/
SELECT * FROM STAGE.STG_CONTACTOS_IVR I
INNER JOIN ODS.ODS_HC_CLIENTES CLI ON CLI.TELEFONO_CLIENTE = I.PHONE_NUMBER;

/* Relleno la tabla de llamadas con los valores correspondientes */
INSERT INTO ODS.ODS_HC_LLAMADAS (ID_IVR, TELEFONO_LLAMADA, ID_CLIENTE, FC_INICIO_LLAMADA, FC_FIN_LLAMADA, ID_DEPARTAMENTO_CC, FLG_TRANSFERIDO, ID_AGENTE_CC, FC_INSERT, FC_MODIFICACION) 
SELECT
ID ID_IVR, 
CASE WHEN LENGTH(TRIM(I.PHONE_NUMBER))<>0 THEN TRIM(I.PHONE_NUMBER) ELSE 9999999999 END TELEFONO_LLAMADA,
CASE WHEN LENGTH(TRIM(CLI.ID_CLIENTE))<>0 THEN TRIM(CLI.ID_CLIENTE) ELSE 999999999 END ID_CLIENTE,
CASE WHEN LENGTH(TRIM(I.START_DATETIME))<>0 THEN STR_TO_DATE(TRIM(I.START_DATETIME), '%Y-%m-%d %H:%i:%S.%f') ELSE STR_TO_DATE('31/12/9999 00:00:00.000000','%d/%m/%Y %H:%i:%S.%f') END FC_INICIO_LLAMADA,
CASE WHEN LENGTH(TRIM(I.END_DATETIME))<>0 THEN STR_TO_DATE(TRIM(I.END_DATETIME), '%Y-%m-%d %H:%i:%S.%f') ELSE STR_TO_DATE('31/12/9999 00:00:00.000000','%d/%m/%Y %H:%i:%S.%f') END FC_FIN_LLAMADA,
DEPT.ID_DEPARTAMENTO_CC ID_DEPARTAMENTO_CC,
CASE WHEN UPPER(I.FLG_TRANSFER) = 'FALSE' THEN 0 ELSE 1 END FLG_TRANSFERIDO,
AG.ID_AGENTE_CC ID_AGENTE_CC,
NOW() FC_INSERT,
NOW() FC_MODIFICACION
FROM STAGE.STG_CONTACTOS_IVR I
LEFT JOIN ODS.ODS_HC_CLIENTES CLI ON CASE WHEN LENGTH(TRIM(I.PHONE_NUMBER)) THEN TRIM(I.PHONE_NUMBER) ELSE 999999999 END = CLI.TELEFONO_CLIENTE
LEFT JOIN ODS_DM_DEPARTAMENTOS_CC DEPT ON CASE WHEN LENGTH(TRIM(I.SERVICE))<>0 THEN UPPER(TRIM(I.SERVICE)) ELSE 'DESCONOCIDO' END = DEPT.DE_DEPARTAMENTO_CC
LEFT JOIN ODS_DM_AGENTES_CC AG ON CASE WHEN LENGTH(TRIM(I.AGENT))<>0 THEN UPPER(TRIM(I.AGENT)) ELSE 'DESCONOCIDO' END = AG.DE_AGENTE_CC
;

COMMIT;
ANALYZE TABLE ODS.ODS_HC_LLAMADAS;


