/* Insertamos en la tabla de hechos de servicios los datos consultados de STAGE.STG_PRODUCTOS_CRRM */

DROP TABLE IF EXISTS ODS.TMP_DIRECCIONES_PRODUCTOS;
CREATE TABLE ODS.TMP_DIRECCIONES_PRODUCTOS AS
SELECT ID_DIRECCION ID_DIRECCION,
DE_DIRECCION DE_DIRECCION,
DE_CP DE_CP,
CIU.DE_CIUDAD DE_CIUDAD,
CIU.DE_ESTADO DE_ESTADO,
PAI.DE_PAIS DE_PAIS
FROM ODS.ODS_HC_DIRECCIONES DIR
INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON CIU.ID_CIUDAD_ESTADO = DIR.ID_CIUDAD_ESTADO 
INNER JOIN ODS.ODS_DM_PAISES PAI ON PAI.ID_PAIS = CIU.ID_PAIS;

COMMIT;
ANALYZE TABLE ODS.TMP_DIRECCIONES_PRODUCTOS;

INSERT INTO ODS.ODS_HC_SERVICIOS (ID_CLIENTE, ID_PRODUCTO, PUNTO_ACCESO, ID_CANAL, ID_AGENTE, ID_DIRECCION_SERVICIO, FC_INICIO, FC_INSTALACION, FC_FIN, FC_INSERT, FC_MODIFICACION)
SELECT CLI.ID_CLIENTE ID_CLIENTE,
OPROD.ID_PRODUCTO ID_PRODUCTO,
CASE WHEN LENGTH(TRIM(SPROD.ACCESS_POINT)) <> 0 THEN TRIM(SPROD.ACCESS_POINT) ELSE 'DESCONOCIDO' END PUNTO_ACCESO, 
CANAL.ID_CANAL ID_CANAL,
CASE WHEN LENGTH(TRIM(SPROD.AGENT_CODE)) <> 0 THEN TRIM(SPROD.AGENT_CODE) ELSE 99999 END ID_AGENTE, 
TMP.ID_DIRECCION ID_DIRECCION_SERVICIO,
CASE WHEN LENGTH(TRIM(SPROD.START_DATE)) <> 0 THEN STR_TO_DATE(TRIM(SPROD.START_DATE), '%d/%m/%Y %T') ELSE STR_TO_DATE('31/12/9999 23:59:59', '%d/%m/%Y %T') END FC_INICIO,
CASE WHEN LENGTH(TRIM(SPROD.INSTALL_DATE)) <> 0 THEN CONVERT(TRIM(REPLACE(SPROD.INSTALL_DATE, 'UTC', '')), DATETIME) ELSE STR_TO_DATE('31/12/9999 23:59:59', '%d/%m/%Y %T') END FC_INSTALACION,
CASE WHEN LENGTH(TRIM(SPROD.END_DATE)) <> 0 THEN CONVERT(TRIM(REPLACE(SPROD.END_DATE, 'UTC', '')), DATETIME) ELSE STR_TO_DATE('31/12/9999 23:59:59', '%d/%m/%Y %T') END FC_FIN,
NOW() FC_INSERT,
NOW() FC_MODIFICACION
FROM STAGE.STG_PRODUCTOS_CRM SPROD
LEFT JOIN ODS.ODS_HC_CLIENTES CLI ON TRIM(SPROD.CUSTOMER_ID) = CLI.ID_CLIENTE
LEFT JOIN ODS_DM_PRODUCTOS OPROD ON CASE WHEN LENGTH(TRIM(SPROD.PRODUCT_NAME))<>0 THEN UPPER(TRIM(SPROD.PRODUCT_NAME)) ELSE 'DESCONOCIDO' END = OPROD.DE_PRODUCTO
LEFT JOIN ODS_DM_CANALES CANAL ON CASE WHEN LENGTH(TRIM(SPROD.CHANNEL))<>0 THEN UPPER(TRIM(SPROD.CHANNEL)) ELSE 'DESCONOCIDO' END = CANAL.DE_CANAL
LEFT JOIN ODS.TMP_DIRECCIONES_PRODUCTOS TMP ON CASE WHEN LENGTH(TRIM(SPROD.PRODUCT_ADDRESS)) <> 0 THEN UPPER(TRIM(SPROD.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END = TMP.DE_DIRECCION
	AND CASE WHEN LENGTH(TRIM(SPROD.PRODUCT_POSTAL_CODE)) <> 0 THEN UPPER(TRIM(SPROD.PRODUCT_POSTAL_CODE)) ELSE 99999 END = TMP.DE_CP  
	AND CASE WHEN LENGTH(TRIM(SPROD.PRODUCT_CITY)) <> 0 THEN UPPER(TRIM(SPROD.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END = TMP.DE_CIUDAD
	AND CASE WHEN LENGTH(TRIM(SPROD.PRODUCT_STATE)) <> 0 THEN UPPER(TRIM(SPROD.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END = TMP.DE_ESTADO 
	AND CASE WHEN LENGTH(TRIM(SPROD.PRODUCT_COUNTRY)) <> 0 THEN UPPER(TRIM(SPROD.PRODUCT_COUNTRY)) ELSE 'DESCONOCIDO' END = TMP.DE_PAIS
;    

COMMIT;
ANALYZE TABLE ODS.ODS_HC_SERVICIOS;

DROP TABLE IF EXISTS ODS.TMP_DIRECCIONES_PRODUCTOS;